version: '3'

tasks:
  linters:
    desc: 'Run linters'
    silent: true
    internal: true
    dir: 'terraform/{{.TF_WORKING_DIR}}'
    cmds:
      - 'terraform fmt -recursive'
  terraform:
    desc: 'Run terraform commands'
    silent: true
    dir: 'terraform/{{.TF_WORKING_DIR}}'
    cmds:
      - task: 'linters'
      - 'terraform {{.CLI_ARGS}}'