variable "region" {}
variable "project_id" {}
variable "aiven_api_token" {}
variable "aiven_project" {}
variable "aiven_region" {}
variable "aiven_kafka_plan" {}
variable "aiven_os_plan" {}
variable "docker_creds" {}
variable "docker_repo" {}
variable "kestra_version" {}
variable "kestra_license_id" {}
variable "kestra_license_key" {}
variable "kestra_license_fingerprint" {}
variable "kestra_encryption_key" {}
variable "ssh_username" {}
variable "ssh_public_key" {}
variable "ssh_private_key" {}
variable "kestra_username" {}
variable "kestra_password" {}
variable "webserver_cidr_range" {}
variable "gcp_vpc" {}